#Makefile for Operating Systems project 2
#Author: Zdenek Dolezal
#Login: xdolez82
#Faculty of Information Technology BUT

CC=gcc
CFLAGS= -std=gnu99 -Wall -Wextra -Werror -pedantic -pthread
NAME=proj2

proj2: $(NAME).c
	$(CC) $(NAME).c -o proj2 $(CFLAGS)
clean:
	rm $(NAME)
