
#MAKEFILE ULTIMATE VERZE

CC=gcc
CFLAGS= -std=c99 -Wall -Wextra -pedantic -Werror

proj2: proj2.c
	$(CC) $(CFLAGS) proj2.c -lm -o proj2
mocniny:
	$(CC) $(CFLAGS) mocniny.c -o mocniny
strtod:
	$(CC) $(CFLAGS) strtod.c -lm -o strtod
clean:
	rm proj2
